services:

  redis:
    image: redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      timeout: 5s
      retries: 5
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: 5hrey45/configserver:latest
    container_name: configserver-ms
    ports:
      - 8071:8071
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      start_period: 10s
      retries: 5
      interval: 10s
      timeout: 5s
    extends:
      file: common-config.yml
      service: microservice-base-config

  eurekaserver:
    image: 5hrey45/eurekaserver:latest
    container_name: eurekaserver-ms
    ports:
      - 8070:8070
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      start_period: 10s
      retries: 5
      interval: 10s
      timeout: 5s
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: eurekaserver
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  accountservice:
    image: 5hrey45/accountservice:latest
    container_name: account-ms
    ports:
      - 8080:8080
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      start_period: 10s
      retries: 5
      interval: 10s
      timeout: 5s
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: accountservice
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  loanservice:
    image: 5hrey45/loanservice:latest
    container_name: loan-ms
    ports:
      - 8081:8081
    healthcheck:
      test: "curl --fail --silent localhost:8081/actuator/health/readiness | grep UP || exit 1"
      start_period: 10s
      retries: 5
      interval: 10s
      timeout: 5s
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: loanservice
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  cardservice:
    image: 5hrey45/cardservice:latest
    container_name: card-ms
    ports:
      - 8082:8082
    healthcheck:
      test: "curl --fail --silent localhost:8082/actuator/health/readiness | grep UP || exit 1"
      start_period: 10s
      retries: 5
      interval: 10s
      timeout: 5s
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: cardservice
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  gatewayserver:
    image: 5hrey45/gatewayserver:latest
    container_name: gatewayserver-ms
    ports:
      - 8072:8072
    depends_on:
      accountservice:
        condition: service_healthy
      loanservice:
        condition: service_healthy
      cardservice:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: gatewayserver
      SPRING_DATA_REDIS_CONNECT-TIMEOUT: 2s
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_TIMEOUT: 1s
    extends:
      file: common-config.yml
      service: microservice-eureka-config

networks:
  bankservice:
    driver: bridge
